CFLAGS=-ansi

all: chars1 chars2 copy1 copy2 digits hello1 hello2 lines longest1 longest2 power0 power1 power2 temps1 temps2 temps3 temps4 temps5 words

clean:
	rm chars1 chars2 copy1 copy2 digits hello1 hello2 lines longest1 longest2 power0 power1 power2 temps1 temps2 temps3 temps4 temps5 words
