CFLAGS=-ansi -pedantic -D_POSIX_C_SOURCE=1

all: chars1 chars2 copy1 copy2 digits hello1 hello2 lines longest1 longest2 power0 power1 power2 temps1 temps2 temps3 temps4 temps5 words

clean:
	# nothing to clean in this directory; use cleanall to delete executables

cleanall: clean
	rm -f chars1 chars2 copy1 copy2 digits hello1 hello2 lines longest1 longest2 power0 power1 power2 temps1 temps2 temps3 temps4 temps5 words
