CFLAGS=-ansi -pedantic

all: binsearch digits atoi shellsort reverse itoa trim

clean:
	# nothing to clean in this directory; use cleanall to delete executables

cleanall: clean
	rm -f binsearch digits atoi shellsort reverse itoa trim
