CFLAGS=-ansi -pedantic

all: atoi bitcount getbits leap lower rand sizes squeeze strcat strlen

clean:
	# nothing to clean in this directory; use cleanall to delete executables

cleanall: clean
	rm -f atoi bitcount getbits leap lower rand sizes squeeze strcat strlen
